### PR TITLE
Milestone 1-6: Responsive Web Design

### PR DESCRIPTION
**Pull request by jebitok-dev**
## TheNextWeb Clone Milestones: 

In these milestones we:

- set-up project and got necessary assets
- analyzed mobile parts and created the skeleton
- applied styling and positioning of elements
- added the media queries 
- deployed and tested the live-version on different screen sizes

### CODE REVIEW

**Review by ioilmio — CHANGES_REQUESTED** [review]
# Hello @jebitok-dev  @KCnick 👋🏼 
## Great job! You are a step away from being approved
### You have done everything required and the project looks very good, the readme file, the PR and the commits messages are also on point, continue  to structure your future project this way, well done! 👌🏼 
## Required changes 🔴 
## Please fix your stylesheets, it is not fully formatted, this way all the checks will pass;
# Quick tip:
## Type  `npx stylelint "**/*.{css,scss}" --fix` in your terminal the --fix flag will do the trick for you, and in most case will solve all your indentation probelm

[OPTIONAL]
Include a screenshot of your application in the readme

#### For any doubt or further info contact me on slack @illuminatosalvatore

**Review by SpaYco — CHANGES_REQUESTED** [review]
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make one more change! 

## Required Changes ♻️ 

- [x] update the live demo in your readme file ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: :eyes:
## Please wait a little bit ...

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Change Required :vertical_traffic_light: :warning: 
## Hello @jebitok-dev and @KCnick  :handshake: :handshake: :handshake: 
:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that your project shows that you have understood all requirements, keep it up :muscle:
### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
## Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] The `live demo link` you were asked to put in the readme file doesn't work. It seems to me that you did not get it right. The following is an easy explanation of the live demo link: You actually need to deploy this project with some existant services such as [GitHack](https://raw.githack.com/), or [Netlify](https://www.netlify.com/), or GitHub pages, or [Heroku](https://heroku.com/), and then the link which showcase a live version of your project online that you will obtain from one of those services is the one which we call `live demo link`, you copy it and paste it in your readme file instead of putting simply livedemo.com, this link redirects nowhere. We expect that if we click on that live demo link, we should see you page opened

- [ ] License and issue links you added to your readme file don't work as well, you should fix that.

:point_up: All of the above required changes will make your repository professional :point_up: 

# [Optional changes] :yellow_circle: 
- [ ] You can add more social network links under the author section
- [ ] You can add screenshot of your cloned page to readme file
- [ ] Make sure that you talk about the work you have done in this project in your readme description section (a summary of 2-3 lines) 

If anything seems to be unclear to you,comment on this Pull Request and mention me as [@descholar-ceo](https://github.com/descholar-ceo)

 | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

**Comment by jebitok-dev** [comment]
The README.md file is on the main branch and it has the live demo link plus the description.

**Comment by descholar-ceo** [comment]
> The README.md file is on the main branch and it has the live demo link plus the description.

Hello @jebitok-dev Thank you for reaching out for clarification:
It should be on this branch as well, because if you merge, the code old code from the main branch will become obselete, but this branch's code will be considered

**Review by elmejdki — APPROVED** [review]
# status: approved :recycle: 
## Great job @team you have made a good clone, thanks for making the required changes.

now you can merge to main, your project is approved.

## Happy Coding :tophat:

**Pull request merged**
